<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?pydev-testrun version="1.0"?><pydev-testsuite>
<summary errors="1" failures="0" finished="true" name="Test Run: 28" tests="0" total_time="Finished in: 0.00 secs."/>
<test location="/home/controller/IoT/cloud/Rest_API_Python/HttpClient/pre_processing/estimate_link_trun.py" status="error" test="estimate_link_trun" time="0">
<stdout/>
<stderr><![CDATA[Traceback (most recent call last):
  File "/home/controller/.p2/pool/plugins/org.python.pydev_5.0.0.201605051159/pysrc/_pydev_runfiles/pydev_runfiles.py", line 468, in __get_module_from_str
    mod = __import__(modname)
  File "/home/controller/IoT/cloud/Rest_API_Python/HttpClient/pre_processing/estimate_link_trun.py", line 80, in <module>
    sum_mean_link_5 += int(list_temp[0])
ValueError: invalid literal for int() with base 10: '5.0353'
ERROR: Module: estimate_link_trun could not be imported (file: /home/controller/IoT/cloud/Rest_API_Python/HttpClient/pre_processing/estimate_link_trun.py).
]]></stderr>
</test>
<launch mode="run">
<launch_memento><![CDATA[<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<launchConfiguration local="true" path="HttpClient estimate_link_trun.py"/>
]]></launch_memento>
</launch>
</pydev-testsuite>
